### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by FOX-user** [vincefn/objcryst#17]
Hi,
thanks a lot for picking up the work of this awesome project again!

I would like to help a bit, so here are little bugs I found and my thoughts about new functions in FOX:

1. Maximize/minimize buttons for 3D crystal view window and PXRD graph view window are missing.

2. Tube alpha1/alpha2 value is not saved, when saving project (should be `<XRayTubeAlpha2Alpha1Ratio>#value#</XRayTubeAlpha2Alpha1Ratio>` in Radiation section, loading works fine, if manually written to save-file)

3. When choosing CuKa1 as radiation, the alpha1/alpha2 value should be set to 0 automatically

4. Decimal points are displayed with the default setting of Windows ("." or ",") in FOX 2016. In older versions it was always "." Adding an option for this in Preferences would be really helpful.

5. "Reset peaks" in right-click menu in show graph window would be helpful, which will reset the "find peaks" operation and the manually added peaks.

6. Spurious lines in quick indexing should be a selectable amount (0-3), because it can take hours to do 3 spurious lines - and especially with manually selected peaks it is not necessary to have 3.

7. A button to export (and maybe import?) the results of indexing would be a nice thing.

The used OS is Windows.

**Comment by vincefn** [comment]
Hi 'FOX-User'- thanks for the feedback. I don't have much time for Fox right now but it's good to have some ideas for improvement.

> 1. Maximize/minimize buttons for 3D crystal view window and PXRD graph view window are missing.

OK - I've played a bit with floating windows, I'll see if the buttons can be added back.

> 2. Tube alpha1/alpha2 value is not saved, when saving project (should be <XRayTubeAlpha2Alpha1Ratio>#value#</XRayTubeAlpha2Alpha1Ratio> in Radiation section, loading works fine, if manually written to save-file)

The value is ignored if the radiation is monochromatic, and therefore not saved.

> 3. When choosing CuKa1 as radiation, the alpha1/alpha2 value should be set to 0 automatically

The value is ignored for a monochromatic radiation. Not sure if this would really help to change it to zero. The alpha1/alpha2 value should just be hidden for a monochromatic radiation.

> 4. Decimal points are displayed with the default setting of Windows ("." or ",") in FOX 2016. In older versions it was always "." Adding an option for this in Preferences would be really helpful.

That can't really be done. This was introduced in Fox to respect the computer locale, and also to be able to use 'validator' objects in the graphical interface, to make sure entered numerical values are correct, and avoid leading to a crash in Fox. I can't add this as an option.

> 5. "Reset peaks" in right-click menu in show graph window would be helpful, which will reset the "find peaks" operation and the manually added peaks.

Is "Hide peaks" not enough to hide the values ? Otherwise re-doing an automatic search will erase any previously searched or added peak.

> 6. Spurious lines in quick indexing should be a selectable amount (0-3), because it can take hours to do 3 spurious lines - and especially with manually selected peaks it is not necessary to have 3.

OK, I'll see about that.

> 7. A button to export (and maybe import?) the results of indexing would be a nice thing.

Not sure what format could be used. Export, maybe. As text ?

**Comment by FOX-user** [comment]
Thanks a lot for your comments and already for your changes - that was really fast!


> The alpha1/alpha2 value should just be hidden for a monochromatic radiation.

That is not the case (at least in Windows)

> > 7. A button to export (and maybe import?) the results of indexing would be a nice thing.

> Not sure what format could be used. Export, maybe. As text ?

That would be really nice! Just a list sorted by score, with cell parameters, cell volume, spurious lines would be good. Actually just the table that is already shown.

**Comment by vincefn** [comment]
>  > The alpha1/alpha2 value should just be hidden for a monochromatic radiation.

> That is not the case (at least in Windows)

Yes, that could be corrected. Note necessarily easy, as the change in monochromatic/tube option does not immediately trigger a GUI refresh event...

> > > 7. A button to export (and maybe import?) the results of indexing would be a nice thing.

> >Not sure what format could be used. Export, maybe. As text ?

> That would be really nice! Just a list sorted by score, with cell parameters, cell volume, spurious lines would be good. Actually just the table that is already shown.

I'll see if that's possible

**Comment by vincefn** [comment]
> 1. Maximize/minimize buttons for 3D crystal view window and PXRD graph view window are missing.


Fixed in c0351c1 (only affected windows)
