### ISSUE TITLE
Request for a new feature

### ISSUE THREAD

**Issue by FOX-user** [vincefn/objcryst#21]
Hi,

I have a request for a new feature, I hope it is possible to realize. I'm sorry, the whole thing is a bit hard to describe. Please let me know if something is unclear.

I am thinking of a new function, which is just the opposite of the anti-bump. With anti-bump, the cost goes up, if 2 atoms come too close to each other.

When someone is trying to solve a structure of a metal-organic framework (for example), it is often known that the carboxylate-oxygen is coordinating to the metal. The metal position is often easy to find with FOX, but getting the linker (an organic rigid body) in the right position, is not possible in most cases.

If FOX could put a cost factor for solutions, where certain atom types are too far away from each other, it should help a lot finding the right solution. The possibility to assign different oxygen-atoms to other types with any name is already there.

Best wishes!

**Comment by vincefn** [comment]
I'm not sure this would work. The main issue is the scaling of the cost function, which is non-trivial. How can you ensure that this penalty function will be properly scaled compared to the powder pattern Chi^2 ? It is very easy to go wrong here.
By comparison, the AntiBump cost function is usually ineffective for that reason. I strongly advise against using it unless you are in some very specific cases where the diffraction data has very low quality and is not enough to solve the structure - e.g. for high pressure data.

Moreover, for the configuration you describe where you know a priori that a ligand is linked to a metalc centre, the more efficient solution is to make a molecule object including the metal atom and the ligand(s).

**Comment by FOX-user** [comment]
The idea I have in mind about this thing is the following:
We have diffraction data, but no idea of the specific structure - that is why we use FOX.
On the other hand, FOX has no idea of any structure at all. What if we could put our knowledge we know about the structure (for example carboxylate coordinates to the metal) into the solution process. I think it would highly increase the structures that could be solved with FOX.

When I try solve a MOF structure, it is always best to use the AntiBump at least for metal-carbon distance. Otherwise FOX would just put the organic ligand into the same position as the metal.

> Moreover, for the configuration you describe where you know a priori that a ligand is linked to a metalc centre, the more efficient solution is to make a molecule object including the metal atom and the ligand(s).

Yes, that is one possibility. But the position of the metal is not known, even if it is known that it is coordinating.
But is it in a plane with both carboxylate oxygens? Is it just coordinating to one of the two oxygens?  Is one carboxylate bridging two metal atoms? What if the metal is in a special position and part of a molecule object?

I have an idea for the new feature: "Chain". If there is a higher distance between the type "metal" and the closest atom of the type "carboxylateO", the cost function is increasing exremely high, so the solution is dropped, and new random moves are tested out.

**Comment by vincefn** [comment]
> We have diffraction data, but no idea of the specific structure - that is why we use FOX.
On the other hand, FOX has no idea of any structure at all. What if we could put our knowledge we know about the structure (for example carboxylate coordinates to the metal) into the solution process. I think it would highly increase the structures that could be solved with FOX.

If you do know _a priori_ that an atom (oxygen) is linked to a metallic center, then the most efficient way of finding the solution is to bind those atom in a single Molecule. It forces **all** the tested configurations to have this bond, instead of just using a cost function which may or may not be properly scaled.

> > Moreover, for the configuration you describe where you know a priori that a ligand is linked to a metalc centre, the more efficient solution is to make a molecule object including the metal atom and the ligand(s).

> Yes, that is one possibility. But the position of the metal is not known, even if it is known that it is coordinating.

That does not matter, the position of the metal atom will be optimised along the bonded atoms.

> But is it in a plane with both carboxylate oxygens? Is it just coordinating to one of the two oxygens? 

You don't need to know in advance. You can link a single atom, and see if the other one ends up being linked in the best solution. Adding a 'bias' in the cost function, if not properly scaled, could link to a wrong solution where two atoms 

> Is one carboxylate bridging two metal atoms? 

You can just bond one metal, and see the final configuration reached. If you have other information (RMN,..) telling you more, you can always create a large molecule with several metal atoms. 

> What if the metal is in a special position and part of a molecule object?

The dynamical occupancy correction will take care of that exactly as if it was a isolated atom. No issue there.

The bottom line is, you have to find the proper sample description including every _a priori_ knowledge in the model. And then the correct configuration is the one which fits the diffraction data best.

In theory, you could use a simple 'attraction' cost function, but there are several issues:
- it is essential not to bias the cost function in an improper way. For example the Antibump cost falls to zero for completely overlapping atoms, or for atoms which are too far - it is _designed_ to be a 'neutral' cost function when a solution is reached:
![tmp](https://user-images.githubusercontent.com/4380511/27587455-bfcbb694-5b44-11e7-8364-43958afa61b6.png)
Your approach would bias against _all_ M-O distances which are too large, even if there will be many which are legitimately larger.

- the scaling of the cost function would be a big issue, especially regarding the added bias as discussed in the previous point

- what is important is not only to have a model or cost function(s) which will properly favour the correct solution, but also will allow the ergodic _search to be explored in an efficient way_. If you bond two atoms in a Molecule, they will _always_ be bonded (one exception is during least squares refinement, where Molecule restraints are effectively weakened, but the atoms are quickly brought back together after that). If, however, you try to do that with a soft cost function, then they will only remain bonded a small amount of the trials - simply because the algorithm is designed to explore the entire configuration space, and will only _statistically_ favour solutions which lower the overall cost functions.

**Comment by FOX-user** [comment]
Thank you for all your explanations and suggestions!
I will try it out like you suggested next time.
