### ISSUE TITLE
Bug report / Grid Calculation

### ISSUE THREAD

**Issue by MatthewKAIST** [vincefn/objcryst#28]
Hello,
I have recently discovered a serious bug and would like to report it.

I am a user using the Korean version of Windows7 64 bit.
When I tried to do grid computing in the FOX program, I noticed that the local client execution button did not work on the server screen.

Also, after executing another FOX program and running the client, connecting to the local server did not normally execute the job.
CPU utilization has not been increased.

**Comment by vincefn** [comment]
Can you tell me which version of Fox you are using?

**Comment by MatthewKAIST** [comment]
The version is 2017.2, Fox-2017-06-28.exe

And I think this version is somewhat slower than the old version (1.9.7. #1313).
Is this happened because of the Non-flip feature?

By the way, the old version works well in the grid computing, even in the same OS & PC :)

**Comment by vincefn** [comment]
The version should not be any slower, though the compiler was updated so there could be a few variations. The non-flip feature cannot influence the calculation speed.

I tested under win 8.1, and just opening Fox (same version), opening the server and using 'run local client' opens another Fox instance (which manages the local clients) which runs correctly jobs when submitted. SO everything OK from my side.

So I don't know what is wrong in your case, but there are plenty of possible issues with the grid client:
- are there non-ascii characters in the full path to the Fox executable ?
- can there be a security setup in windows preventing the launching of a local client ?

**Comment by MatthewKAIST** [comment]
I eventually found that the problem was caused by non-ascii characters in the executable program path.

FOXGrid currently works normally.
The OS I use is Windows 7.1 Professional.

However, it is true that the new version of FOX still feels slower in global optimization than in previous versions.
In particular, even if the same .xml is used, there is a case where the difference in calculation speed is felt.

**Comment by vincefn** [comment]
OK, so as I suspected it was indeed the non-ascii characters in the path which cause the issue. Will take a while to fix, this part of the code is not yet unicode-friendly.

As for the speed, there can be plenty of factors involved, it could depend on the type of structure studied. Since 1.9.7 there were many changes affecting Molecule optimisations, which could slow a bit the number of trials/s but should generally allow converging with fewer trials.. You'll have to supply me with a test case to clarify. Note also I don't have any native windows environment to test (only virtual windows machine).
