### ISSUE TITLE
TOF

### ISSUE THREAD

**Issue by redoxmatlab** [vincefn/objcryst#30]
TOF neutron data (ISIS, three columns) cannot be imported. Please provide an advise on how to sort this out. The problem exist both on windows and mac.

**Comment by vincefn** [comment]
Can you provide an example dataset? 
IIRC there is already a TOF import format for isis, why doesn't it work?
Please provide as much information as possible on this format if it is different.

**Comment by redoxmatlab** [comment]
Sure no problem at all. I'll send you an example by email

**Comment by vincefn** [comment]
The problem lies in your file header, which is:
```
/*
# Bank3 Bank 3
*/
1277.988075    6.781852       0.040062       
```
In the example I had, only the first line needed to be discarded, which is what Fox does now. So if you change the beginning of your file to:
```
# Bank3 Bank 3
1277.988075    6.781852       0.040062       
```
you should be fine.

If there is an official specification for this format ( from the instrument responsible) let me know, it would be welcome, I can update from the 'just ignore the first line' approach.
