### ISSUE TITLE
Rigid Group with multiple atoms leads to an invalid XML

### ISSUE THREAD

**Issue by kuba-v** [vincefn/objcryst#52]
When a Rigid Group is added to a molecule and more then one atom is selected the XML representing the setting has multiple attributes of the name "Atom". For example:
`<RigidGroup Atom="N1" Atom="N2" Atom="C2"/>`
This is an invalid XML as in XML definition says that attribute names should be unique (see e.g. here [Wikipedia XML Attribute](https://en.wikipedia.org/wiki/XML#Key_terminology)).
If such configuration is added it is not possible to open or edit the XML with most XML editors or other frameworks processing XMLs.

**Comment by vincefn** [comment]
Hi - thanks for pointing this out. The use of XML for objcryst/Fox cut a few corners in the design - specifically the xml data cannot be properly _validated_ because I needed a few constraints to include in a true validation (specific elements inside other elements, array of diffraction data of size NxM without the overhead of using an XML element for each value and each row,...), and it was not possible to create a DTD with all those constraints (at least when I wrote this part of the code).

Nevertheless, the XML should be _well-formed_ and this is indeed not the case when there is a RigidGroup. It's easy enough to correct in the code, but the new files will not be backwards-compatible. Not sure if this would affect many people.

PS: unrelated comment - I'm not too fond of rigid groups - they are not very efficient ate helping to find a structure solution and they will not stay strictly rigid (notably during LSQ).
